mvc_statki_02/Models/BattleShipContext.cs
using System.Data.Entity;

namespace mvc_statki_02.Models
{
    class ShipGameContext:DbContext
    {
        public ShipGameContext():base("BattleShipBase")
        {
            
        }
        public DbSet<Player> Players { get; set; }
        public DbSet<Field> Fields { get; set; }
    }
}

mvc_statki_02/Models/Field.cs
namespace mvc_statki_02.Models
{
    public enum State
    {
        Empty,
        Ship,
        Miss,
        Shoted
    }

    public  class Field
    {
        public int PlayerId { get; set; }


        public int Id { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public State State { get; set; }
        
    }
   
}

mvc_statki_02/Models/Player.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace mvc_statki_02.Models
{
    public class Player
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

mvc_statki_02/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using mvc_statki_02.Models;
using mvc_statki_02.ViewModel;
using State = mvc_statki_02.Models.State;

namespace mvc_statki_02.Controllers
{
    public class GameController : Controller
    {
        private int _x = 6;
        private int _y = 6;
        private IList<PlayerViewModel> Players { get; set; }
        public ActionResult ShowMap()
        {
            CreateMap();
            var viewmodel = new List<MapViewModel>();
            using (var db = new ShipGameContext())
            {
                foreach (var player in Players)
                {
                    var fields = db.Fields.Where(x => x.PlayerId == player.Id).ToList();
                    var fieldsVieModel = Mapper.Map<IList<Field>, IList<ViewModelField>>(fields);
                    viewmodel.Add(new MapViewModel { LengthMap = _x, HighMap = _y, NamePlayer = player.Name, IdPlayer = player.Id, Fields = fieldsVieModel });
                }
                viewmodel.First().IdOpponent = viewmodel.Last().IdPlayer;
                viewmodel.Last().IdOpponent = viewmodel.First().IdPlayer;
                viewmodel.First().IsGo = true;

                return View(viewmodel);
            }
        }


        //public ActionResult ShowMap(MapViewModel model)
        //{
        //    var viewmodel1 = new List<MapViewModel>();
        //    bool isHit = false;
        //    var state =
        //        db.Fields.FirstOrDefault(x => x.PlayerId == model.IdOpponent && x.X == model.ShotX && x.Y == model.ShotY);
        //}


           



        [HttpPost]
        public ActionResult ShowMap(MapViewModel model)
        {
            using (var db = new ShipGameContext())
            {
                var viewmodel1 = new List<MapViewModel>();
                bool isHit = false;
                var state =
                    db.Fields.FirstOrDefault(x => x.PlayerId == model.IdOpponent && x.X == model.ShotX && x.Y == model.ShotY);
                if (state.State == State.Ship)
                {
                    db.Fields
                    .Single(x => x.PlayerId == model.IdOpponent && x.X == model.ShotX && x.Y == model.ShotY)
                    .State=State.Shoted;
                    isHit = true;
                }
                if (state.State == State.Empty)
                {
                    db.Fields
                    .Single(x => x.PlayerId == model.IdOpponent && x.X == model.ShotX && x.Y == model.ShotY)
                    .State = State.Miss;
                }

                db.SaveChanges();

                var players =
                    db.Players.ToList();

                foreach (var player in players)
                {
                    var fields = db.Fields.Where(x => x.PlayerId == player.Id).ToList();
                    var fieldsVieModel = Mapper.Map<IList<Field>, IList<ViewModelField>>(fields);
                    viewmodel1.Add(new MapViewModel { LengthMap = _x, HighMap = _y, IdOpponent = players.First(x => x.Id != player.Id).Id, NamePlayer = player.Name, IdPlayer = player.Id, Fields = fieldsVieModel });
                }

                foreach (var map in viewmodel1)
                {
                    if (map.Fields.FirstOrDefault(x=>x.State==ViewModel.State.Ship) == null)
                    {
                        var idWinner = map.IdOpponent;
                        viewmodel1.First(x => x.IdPlayer == idWinner).IsWinner = true;
                        break;
                    }
                }
            

                if (isHit)
                    viewmodel1.First(x => x.IdPlayer == model.IdPlayer).IsGo = true;
                else
                {
                    viewmodel1.First(x => x.IdPlayer == model.IdOpponent).IsGo = true;
                }
                ModelState.Clear();
                return View(viewmodel1);
            }
        }
        private void CreateMap()
        {
            using (var db = new ShipGameContext())
            {
                db.Database.ExecuteSqlCommand("TRUNCATE TABLE [Fields]");
                var rnd = new Random(DateTime.Now.Millisecond);
                var count = db.Players.Count();
                var players = db.Players.OrderBy(x => x.Id).Skip(count - 2).ToList();
                Players = Mapper.Map<IList<Player>, IList<PlayerViewModel>>(players);
                for (int i = 0; i < 2; i++)
                {
                    var list = new List<Field>();

                    for (int j = 0; j < _x; j++)
                    {
                        for (int k = 0; k < _y; k++)
                        {
                            list.Add(new Field { X = j, Y = k, State = State.Empty, PlayerId = Players[i].Id });
                        }
                    }

                    int stateCount = 0;
                    while (stateCount < 6)
                    {
                      stateCount++;
                    }
                    db.Fields.AddRange(list);
                    db.SaveChanges();
                }
            }
        }

       
    }
}

mvc_statki_02/Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mvc_statki_02.Models;

namespace mvc_statki_02.Controllers
{
    public class PlayersController : Controller
    {
        // GET: Authentication
        public ActionResult Login(string player1, string player2)
        {
            if(string.IsNullOrEmpty(player1) == false && string.IsNullOrEmpty(player1) == false)
            {
                using (var db = new ShipGameContext())
                {
                    db.Database.ExecuteSqlCommand("TRUNCATE TABLE [Players]");
                    db.Database.ExecuteSqlCommand("TRUNCATE TABLE [Fields]");
                    //db.Players.Add(new Player { Name = player});

                    db.Players.Add(new Player { Name = player1});
                    db.Players.Add(new Player { Name = player2 });
                    db.SaveChanges();
                }
                return RedirectToAction("ShowMap", "Game");
            }
            return View();
        }
    }
}

mvc_statki_02/Views/Game/GameOver.cshtml
@model  mvc_statki_02.ViewModel.MapViewModel
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>>Ships - game</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Style.css" rel="stylesheet" type="text/css" />
</head>
<body>
<br>
<br>
    @*<div ng-controller="gameoverCtrl">


    </div>*@


    @Html.ActionLink("nowa gra", "ShowMap")
</body>
</html>

mvc_statki_02/Views/Game/ShowMap.cshtml
@{
    ViewBag.Title = "ShowMap";
}


@using mvc_statki_02.ViewModel
@model List<mvc_statki_02.ViewModel.MapViewModel>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ships - game</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Style.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="row">
        <div class="col-md-4">
            <table class="table-bordered">
                <tbody>
                    @for (int i = 0; i < Model.First(x => x.IsGo).HighMap; i++)
                    {
                        
                        <tr>
                            @for (int j = 0; j < Model.First(x => x.IsGo).LengthMap; j++)
                            {
                                if (Model.First(x => x.IsGo).Fields.FirstOrDefault(x => x.X == j && x.Y == i && x.State == State.Ship) != null)
                                {
                                    <td class="style1"></td>
                                }
                                else if (Model.First(x => x.IsGo).Fields.FirstOrDefault(x => x.X == j && x.Y == i && x.State == State.Shoted) != null)
                                {
                                    <td class="Sink">X</td>
                                }
                                else
                                {
                                    <td class="StyleWrong"></td>
                                }

                            }
                        </tr>
                    }
                </tbody>
            </table>
            @Html.DisplayFor(model => model.First(y => y.IsGo).NamePlayer)

        </div>
        
            <div>
                @if (Model.FirstOrDefault(x => x.IsWinner) != null)
                {
                    @Html.Partial("GameOver", Model.First(x => x.IsWinner))
                }
              
            </div>
      
        <div class="col-md-6">
            @Html.Partial("_PartialMapOpponent", Model.First(x => x.IsGo == false))
        </div>
    </div>


















    <div class="col-md-2">


        @using (Html.BeginForm("ShowMap", "Game", FormMethod.Post))
            {
            <div class="form-inline">

                @Html.HiddenFor(x => x.First(y => y.IsGo).IdPlayer)
                @Html.HiddenFor(x => x.First(y => y.IsGo).NamePlayer, Model.First(y => y.IsGo).NamePlayer)
                @Html.HiddenFor(x => x.First(y => y.IsGo).IdOpponent, Model.First(y => y.IsGo).IdOpponent)

                <label>Poziomo: </label>
                @Html.DropDownListFor(x => x.First(y => y.IsGo).ShotX, new SelectList(Enumerable.Range(0, 6)))
               
                <label>Pionowo: </label>
                @Html.DropDownListFor(x => x.First(y => y.IsGo).ShotY, new SelectList(Enumerable.Range(0, 6)))
                <br>
                <div class="form-group">
                    <div>
                        <input type="submit" value="GO" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
        </div>

</body>
</html>

mvc_statki_02/Views/Game/_PartialMapOpponent.cshtml
@using mvc_statki_02.ViewModel
@model MapViewModel
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ships - game</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Style.css" rel="stylesheet" type="text/css" />
</head>
<body>

<table class="table-bordered">
    <tbody>
    @for (int i = 0; i < Model.HighMap; i++)
    {
        <tr>
            @for (int j = 0; j < Model.LengthMap; j++)
            {
                if (Model.Fields.FirstOrDefault(x => x.X == j && x.Y == i && x.State == State.Miss) != null)
                {
                    <td class="Fail"> . </td>
                }
                else if (Model.Fields.FirstOrDefault(x => x.X == j && x.Y == i && x.State == State.Shoted) != null)
                {
                    <td> X </td>
                }
                else
                {
                    <td class="StyleWrong"></td>
                }

            }
        </tr>
    }
    </tbody>
</table>
   @Html.DisplayFor(model => model.NamePlayer)
</body>
</html>

mvc_statki_02/Views/Players/Login.cshtml
@{
    ViewBag.Title = "Login";
}

@using (Html.BeginForm("Login", "Players", FormMethod.Post))
{
    <br>
    <div class="col-md">
        <div class="col-md-10 ">
            <label>Player 1 nick: </label>
            @Html.TextBox("player1")<br>
        </div>
        <div class="col-md-10">
            <label>Player 2 nick: </label>
            @Html.TextBox("player2")
            <div class="form-group">
                <button type="submit" class="btn btn-default"> GO </button>
            </div>
        </div>
           
        </div>
}
      


      

mvc_statki_02/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />

    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
   
<div class="container body-content">
    @RenderBody();
    
   
</div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>